### ISSUE TITLE
Guide needed for setting up build environment on new install

### ISSUE THREAD

**Issue by kiltedkoder** [project-trident/trident-docs#6]
When I install this, I don't know what packages I need so that I can start compiling things.  
I have llvm80 installed and i installed the qt tools, but when I run qmake I get:
```Project Error: Cannot run compiler 'clang++'.```

Maybe include a simple script with the install that will 'pkg install' all the necessary pkgs and configs?

**Comment by beanpole135** [comment]
just install the "os-generic-userland-devtools" package, that is the only one needed. I have not written anything up because this is the 3rd name change of that package so far and I want to make sure it has stabilized upstream before we publish anything about it.

**Comment by kiltedkoder** [comment]
Thanks beanpole135!
